"""回合加重開次數

Revision ID: 5ac734c9cc76
Revises: 643ae9045afb
Create Date: 2026-09-07 22:49:34.994634
"""
from alembic import op
import sqlalchemy as sa


revision = '5ac734c9cc76'
down_revision = '643ae9045afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('reopen_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'reopen_count')
    # ### end Alembic commands ###
