"""v2 初始結構

Revision ID: 643ae9045afb
Revises: 
Create Date: 2026-09-07 22:17:48.544528
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '643ae9045afb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precedents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('addr', sa.String(), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('origin_table_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tables',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('recruiting', 'running', 'awaiting_adjudication', 'finished', name='table_status'), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('global_hour', sa.Integer(), nullable=False),
    sa.Column('tick_hours', sa.Integer(), nullable=False),
    sa.Column('max_ticks', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('shared_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'tick', 'side', name='uq_brief')
    )
    op.create_index(op.f('ix_briefs_table_id'), 'briefs', ['table_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('clause_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('issued_gh', sa.Integer(), nullable=False),
    sa.Column('effective_gh', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('units', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('supersedes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('superseded_by', sa.String(), nullable=True),
    sa.Column('phase', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('predicate', sa.Text(), nullable=True),
    sa.Column('consumed_gh', sa.Integer(), nullable=True),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'clause_id', name='uq_clause')
    )
    op.create_index(op.f('ix_clauses_table_id'), 'clauses', ['table_id'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dossier_hash', sa.String(), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_table_id'), 'dossiers', ['table_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_table_id'), 'events', ['table_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'side', 'idempotency_key', name='uq_order_idem'),
    sa.UniqueConstraint('table_id', 'tick', 'side', 'version', name='uq_order_version')
    )
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_table('pending',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('pending_id', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('clause_id', sa.String(), nullable=True),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'pending_id', name='uq_pending')
    )
    op.create_index(op.f('ix_pending_table_id'), 'pending', ['table_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'question_id', name='uq_question')
    )
    op.create_index(op.f('ix_questions_table_id'), 'questions', ['table_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reopened', 'ready', 'registering', 'resolving', 'committed', name='round_status'), nullable=False),
    sa.Column('window_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('lease_worker', sa.String(), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'tick', name='uq_round')
    )
    op.create_index(op.f('ix_rounds_table_id'), 'rounds', ['table_id'], unique=False)
    op.create_table('rulings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('ruling_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('body', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('beneficiary_actual', sa.String(), nullable=True),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'ruling_id', name='uq_ruling')
    )
    op.create_index(op.f('ix_rulings_table_id'), 'rulings', ['table_id'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('allies', 'axis', 'referee', 'observer', name='seat_role'), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'role', 'label', name='uq_seat'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_seats_table_id'), 'seats', ['table_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_table_id'), 'signals', ['table_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'gh', name='uq_snapshot')
    )
    op.create_index(op.f('ix_snapshots_table_id'), 'snapshots', ['table_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('table_id', sa.String(), nullable=False),
    sa.Column('gh', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('dossier_id', sa.String(), nullable=True),
    sa.Column('decision', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('validation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('execution', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('end_state_hash', sa.String(), nullable=True),
    sa.Column('committed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_id', 'gh', 'kind', 'attempt', name='uq_decision_attempt')
    )
    op.create_index(op.f('ix_decisions_table_id'), 'decisions', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_table_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_snapshots_table_id'), table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_signals_table_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_seats_table_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index(op.f('ix_rulings_table_id'), table_name='rulings')
    op.drop_table('rulings')
    op.drop_index(op.f('ix_rounds_table_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_questions_table_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_pending_table_id'), table_name='pending')
    op.drop_table('pending')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_events_table_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_dossiers_table_id'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_clauses_table_id'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_briefs_table_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_table('tables')
    op.drop_table('precedents')
    # ### end Alembic commands ###
